quarkus.resteasy.problem.constraint-violation.status=422
quarkus.resteasy.problem.constraint-violation.title=Constraint violation

mp.openapi.filter=com.github.nderwin.error.handling.control.GlobalErrorResponseFilter
