quarkus.virtual-threads.enabled=true
quarkus.http.io-threads=8

#mp.messaging.incoming.orders.connector=smallrye-kafka
#mp.messaging.incoming.orders.topic=orders
#mp.messaging.incoming.orders.value.deserializer=org.apache.kafka.common.serialization.StringDeserializer

quarkus.kafka.devservices.enabled=false
