otel.sdk.disabled=false
otel.javaagent.enabled=true
otel.javaagent.debug=false

# 4318
otel.exporter.otlp.endpoint=http://localhost:4318
otel.exporter.otlp.protocol=http/protobuf

otel.service.name=JBoss

otel.instrumentation.hibernate.experimental-span-attributes=true

otel.instrumentation.common.db-statement-sanitizer.enabled=false
otel.instrumentation.jdbc.statement-sanitizer.enabled=false
otel.instrumentation.jdbc.capture-parameters=true
