quarkus.datasource.db-kind=postgresql

quarkus.hibernate-orm.log.sql=true
quarkus.hibernate-orm.quote-identifiers.strategy=only-keywords
quarkus.hibernate-orm.schema-management.strategy=drop-and-create

%dev.quarkus.log.category."com.github.nderwin".level=DEBUG

quarkus.flags.runtime."new-ui".value=false
quarkus.flags.runtime."api-v2".value=true
