quarkus.langchain4j.ollama.chat-model.model-name=qwen3-vl:8b-instruct-q8_0

quarkus.langchain4j.ollama.embedding-model.model-name=nomic-embed-text:latest

quarkus.langchain4j.ollama.timeout=60s

quarkus.langchain4j.log-requests=false
quarkus.langchain4j.log-responses=false

quarkus.datasource.db-kind=postgresql

quarkus.langchain4j.pgvector.table=embeddings
quarkus.langchain4j.pgvector.drop-table-first=true
quarkus.langchain4j.pgvector.create-table=true

quarkus.langchain4j.pgvector.dimension=768
quarkus.langchain4j.pgvector.use-index=true
quarkus.langchain4j.pgvector.index-list-size=10

quarkus.docling.devservices.enable-ui=true
quarkus.docling.timeout=3M

quarkus.rest-client."io.quarkiverse.docling.runtime.client.DoclingService".connect-timeout=60
quarkus.rest-client."io.quarkiverse.docling.runtime.client.DoclingService".read-timeout=300
